### ISSUE TITLE
Support for millisecond timestamp

### ISSUE THREAD

**Issue by wladston** [seidtgeist/ng-time-relative#1]
If the value being supplied as a date is invalid, try parsing it as a milliseconds since epoch timestamp.

**Comment by seidtgeist** [comment]
Strange, [moment.js should already support this](http://momentjs.com/docs/#/parsing/unix-offset/)

Maybe it doesn't work because we're passing in the number as a string?

**Comment by wladston** [comment]
yes .. I got around this issue doing this:

``` html
<time class="relative" datetime="{{ thread.modified|date }}">a while ago</time>
```

I wonder why it doesn't work directly ...
