### ISSUE TITLE
`moment.lang` deprecated

### ISSUE THREAD

**Issue by boennemann** [seidtgeist/ng-time-relative#11]
As of moment@2.8.1 `moment.lang` is deprecated and was replaced by `moment.locale`. http://momentjs.com/docs/#/i18n/changing-locale/

As one may provide their own instance of moment this may cause issues.

There are two possible ways to fix this:
1. Bump the moment dependency from ~2.0.0 to ^2.8.1 and use `moment.locale`
2. 

``` js
var locale = typeof moment.locale === 'function' ? 'locale' : 'lang'
// …
moment[locale]('en')
```

Changing ~2.0.0 to ^2.0.0 would still be recommended though.

What do you think? Not so sure, but I think I prefer 2.

**Comment by seidtgeist** [comment]
I also prefer version 2 and yes let's change the version to ^2.0.0.
